dist: xenial
language: python
sudo: false
cache: pip
branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: pypy2.7-6.0
      env: TOXENV=pypy
    - python: pypy3.5-6.0
      env: TOXENV=pypy3
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=checkmanifest
    - os: linux
      env:
        - TOXENV=32bit INSTALL_REQUIREMENTS="apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -yq python3 locales python3-pip python3-tox debianutils; pip3 install; locale-gen en_US.UTF-8"


install:
  - pip install tox
script:
  - tox
after_success:
  - pip install coveralls
  - coveralls
